//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManagement_Assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Account()
        {
            this.Record = new HashSet<Record>();
        }
    
        public string Account_ID { get; set; }
        public string ID_Number { get; set; }
        public string Name { get; set; }
        public Nullable<double> Money { get; set; }
        public string Account_Type { get; set; }
        public Nullable<System.DateTime> Opening_Time { get; set; }
        public Nullable<int> Terms { get; set; }
        public Nullable<double> Rate { get; set; }
        public string Password { get; set; }
        public Nullable<double> Fixed_deposit { get; set; }
        public Nullable<System.DateTime> 到期时间 { get; set; }
        public byte[] Picture { get; set; }
        public Nullable<byte> 是否按规定存款 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Record> Record { get; set; }
    }
}
