//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManagement_Assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employer
    {
        public string Employer_ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public Nullable<double> Sallery { get; set; }
        public Nullable<byte> is_Administrator { get; set; }
        public string Password { get; set; }
        public byte[] Picture { get; set; }
    }
}
