//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManagement_Assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rate
    {
        public string ID { get; set; }
        public string Types { get; set; }
        public Nullable<int> Terms { get; set; }
        public Nullable<double> Rate1 { get; set; }
        public Nullable<double> Rate2 { get; set; }
        public Nullable<double> Rate3 { get; set; }
    }
}
