//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankManagement_Assignment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public string Record_ID { get; set; }
        public Nullable<double> Trading_Amount { get; set; }
        public System.DateTime Trading_Time { get; set; }
        public string Account_ID { get; set; }
        public Nullable<double> Capital { get; set; }
        public Nullable<double> Interest { get; set; }
        public string Operation_Type { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
